name: Build and Test Avalonia App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test --no-build --configuration Release --verbosity normal

      - name: Create Artifacts Directory
        run: mkdir -p ./artifacts

      - name: Publish Build Artifacts
        run: dotnet publish --configuration Release -o ./artifacts

      - name: Verify Artifacts Directory
        run: ls -la ./artifacts

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Avalonia-App
          path: ./artifacts
